INSERT INTO devs (name, skillOne, skillTwo, skillThree, photo, yearsExp, github, linkedin, portfolio, bio, businessOne, businessTwo, businessThree)
VALUES ('Aimes', 'JavaScript', 'Node.js', 'SQL', 'www.aimes.com/aimes.jpg', 2, 'www.github.com', 'www.linkedin.com', 'www.portfolio.com', 'blah', 'Apple', 'Google', 'Amazon');

INSERT INTO devs (name, skillOne, skillTwo, skillThree, photo, yearsExp, github, linkedin, portfolio, bio, businessOne, businessTwo, businessThree)
VALUES ('Adrian', 'Bootstrap', 'jQuery', 'Express.js', 'www.adrian.com/adrian.jpg', 7, 'www.github.com', 'www.linkedin.com', 'www.portfolio.com', 'blah', 'Match', 'Deloitte', 'Apple');

INSERT INTO devs (name, skillOne, skillTwo, skillThree, photo, yearsExp, github, linkedin, portfolio, bio, businessOne, businessTwo, businessThree)
VALUES ('Vince', 'JavaScript', 'React.js', 'SQL', 'www.vince.com/vince.jpg', 5, 'www.github.com', 'www.linkedin.com', 'www.portfolio.com', 'Apple', 'blah', 'Match', 'Google');



INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Apple', 'React', 'mySQL', 'Node.js', 'www.apple.com', 'www.apple.com/apple.jpg', '123 fake st', 'blah', 'job');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Google', 'Angular', 'Firebase', 'Express.js', 'www.google.com', 'www.google.com/google.jpg', '123 fake st', 'blah', 'job');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Amazon', 'React', 'Node.js', 'Express.js', 'www.amazon.com', 'www.amazon.com/amazon.jpg', '123 fake st', 'blah', 'job');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Germ Blast', 'Javascript', 'Node.js', 'Express.js', 'www.germblast.com', 'https://media.everythinglubbock.com/nxsglobal/everythinglubbock/photo/2016/04/19/White%20Background_1461086852826_8163186_ver1.0_1280_720.jpg', '1414 Avenue j dallas, tx', 'GermBlast is excited to add another programmer to its development team. We are currently developing some new systems using React and Node/Express.js. The ideal candidate will have some experience with both front end and back end programming', 'Javascript Programmer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Koingo IT & Web Solutions', 'MySQL', 'CSS', 'javascript', 'www.koingoit.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Logo-kemkominfo-id.svg/1200px-Logo-kemkominfo-id.svg.png', '3010 Lyndon B Johnson FWY #745, Dallas, TX 75234', 'Experience developing Microsoft-based enterprise web applications. Hands-on experience using Visual Studio .NET and .NET Framework. Strong knowledge of Microsoft SQL Server, stored procedures, and triggers. Experience with Linux Server Environment Management/Deployment and MySQL', 'web programmer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('IT Applications Trainee', 'MYSQL', 'Node.js', 'Express.js', '', 'https://totalmedsolutions.com/wp-content/uploads/2017/04/total-Med-solutions-logo-280.png', '5445 La Sierra drive, Dallas, TX 75231', 'Develops an understanding of Sedgwicks IT processes and procedures, including the software development life cycle. Develops skills and knowledge in required development language to perform assigned tasks. Under close supervision, assists in the performance of the following duties: Data and system analysis, including loading and balancing creation of derived fields and formatting, process flows and data diagrams.', 'IT Applications');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Cobalt', 'Javascript', 'jquery', 'Node.js', 'https://www.cobalt.net/', 'https://www.cobalt.net/wp-content/themes/cobalt-2017/images/logo.png', '2511 Richmond Hwy #850, Arlington, VA 22202', 'We currently have an opening for an entry level C# Programmer for product development, client implementations, and sustainment of Cobalt’s products. Our products are mobile and browser-based CRM applications that make substantial use of web services. These applications are built on top of the Microsoft Dynamics CRM and Dynamics365 platforms. This position will play a primary role on our cross functional SCRUM team, and candidates must be interested in working closely with a small team of technical individuals to produce excellent quality products and implementations while focusing on code reusability and flexibility.', 'Javascript Programmer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('CTDI', 'React', 'mySQL', 'Javascript', 'https://www.ctdi.com/', 'http://file02.ctdi.com/Corp.Internal.CTDIWebsite/assets/images/ctdi-logo.png', '701 Lakeside Pkwy, Flower Mound, TX 75208', 'This entry level developer position will work both independently and in a team with other Programmers with a focus on writing code and developing applications leveraging multiple tools, languages, processes, and technologies. Development will ensure that the technical solutions meet the business needs and are developed and implemented with high quality following agreed upon standards. The ideal candidate will have a passion for learning and be able to adapt to changing tasks quickly.', 'Communications design');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Affinity Energy LLC', 'React', 'mySQL', 'Node.js', 'https://www.affinityenergy.com/', 'https://www.affinityenergy.com/wp-content/uploads/2016/02/affinity-energy-logo.svg#aqua_resizer_image_not_accessible', '11900 Sam Roper dr, Charlotte, NC 28269', 'Our company provides systems and services that allow mission critical facilities and distributed generation plants to operate safely, efficiently, and reliably. Specifically, we design, implement, install and support controls, instrumentation, and monitoring systems.', 'Database Programmer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Buckeye Insurance Group', 'Express', 'CSS', 'Javascript', 'http://www.buckeye-ins.com/', 'http://www.buckeye-ins.com/images/logo.png', '1 Heritage Pl, Piqua, OH 45356', 'Work with teams on new applications/functionality. Support break/fix items for applications. Detail documentation of all changes/processes. Provide technical support for application issues', 'Web Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('PTAC Consulting Engineers', 'HTML', 'CSS', 'Express', 'https://www.ptac.com/', 'https://static.wixstatic.com/media/37457b_f9f10c71e6f149d5b0b654ac39e82c4e~mv2.png/v1/fill/w_213,h_100,al_c,q_80,usm_0.66_1.00_0.01/37457b_f9f10c71e6f149d5b0b654ac39e82c4e~mv2.webp', '28490 2nd street, Ste A Daphne, AL 36526', 'PTAC Consulting Engineers is seeking a Software Developer to help develop our software, EDGE^Cloud. The EDGE platform facilitates project design, estimation, production, erection, and much more for the prestressed precast concrete industry. Our goal is to help the precast concrete industry by producing software that allows users to easily produce detailed 3D models which can be translated into accurate bills of materials and shop tickets, allowing a more seamless workflow from the estimation phase through the erection phase. As part of the team, you will help transform the precast concrete industry by providing innovative solutions to an antiquated workflow.', 'Web Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Straightline HDD inc', 'Jquery', 'mySQL', 'HTML', 'https://www.straightlinehdd.com/', 'https://www.straightlinehdd.com/images/logo.png?1520884058', 'Hutchinson, KS 67501', 'In-house Web Applications Developer primarily focused on web programming for e-commerce, informational, and internal utility web sites for Yoder Smokers/StraightLine HDD/ Source HDD.', 'Web Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('ENACOMM inc', 'React', 'mySQL', 'Javascript', 'http://www.enacomm.net/Enacomm-home-login/index.html', 'https://s3.amazonaws.com/bankerad-production-bucketsec/vendors/vendor_logos/000/001/082/original/enacomm-2color_%281%29.png?1489599034', '5800 E Skelly Dr, Tulsa, OK 74135', 'Develops and enhances new and existing web applications and web services. Works with the development team to estimate feature tasks and plan sprints. Innovates with other developers and project managers to continually improve our products. Brings a great attitude that contributes to a fun, cooperative, and productive work environment. Helps maintain and enhance software development lifecycle practices. Stays up to speed on the latest enhancements to the .Net platform', 'Web Developer');


INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Alexis', 'Javascript', 'HTML', 'CSS', 'https://shop-alexis.com/', 'https://shop-alexis.com/', 'Miami, FL ', 'ALEXIS is seeking a full stack developer for coding and modifying our E-Commerce website, from layout to function. We are looking for someone that can incorporate best practices in UI/UX.', 'Web Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Veer West', 'HTML', 'CSS', 'Javascript', 'https://www.formassembly.com/team/', 'https://pbs.twimg.com/profile_images/715735568982810624/2OTD_VNX_400x400.jpg', '101 W Kirkwood Ave #244, Bloomington, IN 47404', 'As a Web Designer and Developer at FormAssembly you will be responsible for the design, implementation, testing and creation of web pages and assets on formassembly.com. Your primary responsibilities will include managing the website, optimizing assets (site speed, code structure, plugins, etc.), creating landing pages, and managing our website presence', 'Web Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Human Mode', 'Express', 'mySQL', 'Node.js', 'https://www.humanmode.com/', 'http://www.humanmode.com/wp-content/uploads/2018/02/humanmodelogo2.jpg', '4005 NW Expressway Ste 610, Oklahoma City, OK 73116', 'Are you a network programming wizard? Are you more likely to name your first born JSON than Jason? Do you do more cURLs than a championship body builder? If so, then we’d like to get to know you. Human Mode is an Oklahoma City based research and technology company focused on the future of Virtual Reality and Augmented reality games and applications. We’re looking for an amazing full stack web application developer with strong back-end experience and a keen ability to connect platforms. This individual will help us build the informational bridges between our games and other applications. Qualified applicants must have secure coding experience and place a strong emphasis on building secure and efficient server resources.', 'Web Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Gammill inc', 'MySQL', 'Javascript', 'HTML', 'https://gammill.com/', 'https://gammill.com/', '1452 Gibson St, West Plains, MO 65775', 'Gammill Inc in Columbia MO is seeking a full time onsite Web / Database developer to support and develop existing and new systems. Small team environment requires willingness to take initiative when opportunity presents itself.', 'MYSQL developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Austin Lane Technologies inc', 'Express', 'mySQL', 'Javascript', 'https://www.austinlane.com/', 'https://www.austinlane.com/images/AL_LogoWithIcon_NAVY.png', '421 E Hickory st #104, Denton, TX 76201', 'In the fast-paced world of Austin Lane Technologies Inc., you will collaborate with highly-skilled software professionals and face new and exciting challenges daily. We are passionate about our work and are inspired by the impact our simple and powerful software has on our clients and their businesses. By joining the Austin Lane team, you will be provided with a world of opportunities.', 'Web Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Amica Insurance Company', 'Javascript', 'mySQL', 'Express', 'https://amica.amicacoverage.com', 'http://boisemetroidcoc.weblinkconnect.com/external/wcpages/wcwebcontent/webcontentpage.aspx?contentid=4683', 'Lincoln, RI', 'Our office located in Lincoln, RI is seeking entry-level IT Developers to work in our CIS department. The position involves providing application development and support for our insurance systems.', 'IT Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('The Boss Group', 'HTML', 'CSS', 'Javascript', 'https://www.thebossgroup.com/', 'https://www.thebossgroup.com/static/assets/images/logo/2color-No-tag.png', '5307 E Mockingbird Ln, Dallas, TX 75206', 'Fantastic opportunity for a Front End Developer! Our client is seeking a talented Front End Developer for an ongoing temporary hire currently located in Dallas, TX. For this position, we are seeking a Front-End Web Developer who is motivated to combine the art of design with the science of programming. Responsibilities will include translation of the UI/UX design wireframes to actual code that will produce visual elements of the application. You will work with talented UI/UX designers and bridge the gap between graphical design and technical implementation, taking an active role on both sides and defining how the application appears as well as how it performs.', 'Front End Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Rekruiters', 'Javascript', 'HTML', 'CSS', 'https://rekruiters.com/', 'https://rekruiters.com/wp-content/uploads/rekruiters-logo.png', '11111 Katy Fwy #310, Houston, TX 77079', 'Our client is looking for a self-driven Front-end Developer to join their team. The candidate will be responsible for implementing visual elements that users see and interact within various web applications used by internal employees for our client.The ideal candidate should possess a combination of programming skills (Angular, HTML, CSS, JS, etc.) and aesthetics (understanding element arrangements on the screen, the color and font choices, and so on) as well as a solid understanding of client and server development, and all major desktop and mobile browser behaviors, responsive web design techniques, and interface defect troubleshooting.', 'Front-end Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('Ansira', 'Javascript', 'Jquery', 'HTML', 'https://ansira.com/', 'https://lever-client-logos.s3.amazonaws.com/ae3984a5-3edc-4587-89b2-2a2980b7522f-1539293329024.png', 'Three Galleria Tower, Noel rd #600, Dallas, TX 75240', 'Ansira is a leading marketing technology and services firm that helps brands orchestrate, personalize and contextualize customer engagements to drive superior business results. Our firm is comprised of strategists, technologists, data scientists, creatives and channel experts who support over 150 brands from verticals such as auto, retail and QSR to insurance, hospitality and energy. Ansira is backed by Advent International, one of the largest and most experienced global private equity investors, with deep expertise in the business and financial services sector.', 'Front-end Developer');

INSERT INTO businesses (name, skillOne, skillTwo, skillThree, website, photo, address, bio, job_description)
VALUES ('iTrellis', 'React', 'Javascript', 'Node.js', 'https://www.itrellis.com/', 'https://www.itrellis.com/static/images/iTrellis_Logo_White.png', '1411 4th Ave, Seattle, WA 98104', 'Our focus is on real-world problems and real-world solutions. The keys to our success are our focus on continuous improvement of both our employees and our company, our dedication to keeping up with current and emerging technologies, and our commitment to delivering complete solutions. Our consultants come from all backgrounds, from self-taught to coding boot camp graduates to academics with advanced degrees. Regardless of our years of experience, there are always more things to learn, and we need you to help us grow; let us help you grow too!', 'Front End Developer');

